package gov.pr.celepar.tabeliao.pojo;
// Generated 01/09/2006 13:27:07 by J-Querena using Hibernate Tools 3.1.0.beta5
/*
Este programa é licenciado de acordo com a 
LPG-AP (LICENÇA PÚBLICA GERAL PARA PROGRAMAS DE COMPUTADOR DA ADMINISTRAÇÃO PÚBLICA), 
versão 1.1 ou qualquer versão posterior.
A LPG-AP deve acompanhar todas PUBLICAÇÕES, DISTRIBUIÇÕES e REPRODUÇÕES deste Programa.
Caso uma cópia da LPG-AP não esteja disponível junto com este Programa, 
você pode contatar o LICENCIANTE ou então acessar diretamente:
http://www.celepar.pr.gov.br/licenca/LPG-AP.pdf
Para poder USAR, PUBLICAR, DISTRIBUIR, REPRODUZIR ou ALTERAR este Programa 
é preciso estar de acordo com os termos da LPG-AP
*/

import java.util.HashSet;
import java.util.Set;

/**
 * Classe POJO para Autoridade Certificadora.
 * Ac generated by hbm2java
 */
public class Ac  implements java.io.Serializable {

    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -5669432691893251998L;
	private long id;
     private Ac pai;
     private String nome;
     private String dn;
     private Set<Ac> filhos = new HashSet<Ac>(0);
     private Set<CertificadoAc> certificadosAc = new HashSet<CertificadoAc>(0);

     // Constructors

    /** default constructor */
    public Ac() {
    }

    /**
     * minimal contructor
     * @param id
     * @param nome
     * @param dn
     */
    public Ac(long id, String nome, String dn) {
        this.id = id;
        this.nome = nome;
        this.dn = dn;
    }
    
    /**
     * full constructor
     * @param id
     * @param pai
     * @param nome
     * @param dn
     * @param filhos
     * @param certificadosAc
     */
    public Ac(long id, Ac pai, String nome, String dn, Set<Ac> filhos, Set<CertificadoAc> certificadosAc) {
       this.id = id;
       this.pai = pai;
       this.nome = nome;
       this.dn = dn;
       this.filhos = filhos;
       this.certificadosAc = certificadosAc;
    }
    
   
    /**
     * 
     * @return numero identificador na base
     */
    public long getId() {
        return this.id;
    }
    
    /**
     * 
     * @param id
     */
    public void setId(long id) {
        this.id = id;
    }
    
    /**
     * 
     * @return Autoridade Certificadora de Nivel imediatamente superior.
     */
    public Ac getPai() {
        return this.pai;
    }
    
    /**
     * 
     * @param pai Autoridade Certificadora de Nivel imediatamente superior.
     */
    public void setPai(Ac pai) {
        this.pai = pai;
    }
    
    /**
     * 
     * @return Nome da Autoridade Certificadora
     */
    public String getNome() {
        return this.nome;
    }
    
    /**
     * 
     * @param nome Nome da Autoridade Certificadora
     */
    public void setNome(String nome) {
        this.nome = nome;
    }
    
    /**
     * 
     * @return Distinguished Name
     */
    public String getDn() {
        return this.dn;
    }
    
    /**
     * 
     * @param dn Distinguished Name
     */
    public void setDn(String dn) {
        this.dn = dn;
    }
    
    /**
     * 
     * @return Autoridades Certificadoras de nivel imediatamente inferior
     */
    public Set<Ac> getFilhos() {
        return this.filhos;
    }
    
    /**
     * 
     * @param filhos Autoridades Certificadoras de nivel imediatamente inferior
     */
    public void setFilhos(Set<Ac> filhos) {
        this.filhos = filhos;
    }
    
    /**
     * 
     * @return quantidade de Autoridades Certificadoras de nivel imediatamente inferior
     */
    public int getQtdeFilhos(){
    	return filhos.size();
    }
    
    /**
     * 
     * @return Conjunto de certificados armazenados para a Autoridade Certificadora
     */
    public Set<CertificadoAc> getCertificadosAc() {
        return this.certificadosAc;
    }
    
    /**
     * 
     * @param certificadosAc Conjunto de Certificados a serem armazenados para a Autoridade Certificadora
     */
    public void setCertificadosAc(Set<CertificadoAc> certificadosAc) {
        this.certificadosAc = certificadosAc;
    }
    
    /**
     * Adiciona um certificado de Autoridade.
     * @param certificadoAc 
     */
    public void addCertificadoAc(CertificadoAc certificadoAc) {
    	certificadosAc.add(certificadoAc);
    }

    /**
     * Remove um certificado de Autoridade
     * @param certificadoAc
     */
    public void removeCertificadoAc(CertificadoAc certificadoAc) {
    	certificadosAc.remove(certificadoAc);
    }
}


